# Generated by Django 5.0.6 on 2024-07-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0002_customuser_delete_simpleuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("batch_name", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
